// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Jesof

pub const SERVER_ADDR: &str = "SERVER_ADDR";
pub const ROUTERS_CONFIG: &str = "ROUTERS_CONFIG";
pub const COLLECTION_INTERVAL_SECONDS: &str = "COLLECTION_INTERVAL_SECONDS";
pub const GAP_RESET_THRESHOLD_SECONDS: &str = "GAP_RESET_THRESHOLD_SECONDS";
pub const STARTUP_CONNECTIVITY_TEST: &str = "STARTUP_CONNECTIVITY_TEST";
pub const STARTUP_CONNECTIVITY_TIMEOUT_SECS: &str = "STARTUP_CONNECTIVITY_TIMEOUT_SECS";
pub const STRICT_STARTUP_MODE: &str = "STRICT_STARTUP_MODE";
pub const ROUTEROS_ADDRESS: &str = "ROUTEROS_ADDRESS";
pub const ROUTEROS_USERNAME: &str = "ROUTEROS_USERNAME";
pub const ROUTEROS_PASSWORD: &str = "ROUTEROS_PASSWORD";
